import type { Metadata } from "next";
import SiteHeader from "@/components/site-header";
import SiteFooter from "@/components/site-footer";
import { getLocaleFromCookie, t } from "@/lib/i18n";
export const metadata:Metadata={title:"About — Tranos Studio",description:"Tranos is a digital and AI creative studio built around clarity, craft and technology."};
export default async function AboutPage(){
 const locale=await getLocaleFromCookie();const tr=(key:Parameters<typeof t>[1])=>t(locale,key);
 return <><SiteHeader/><main className="tx-inner-page"><section className="tx-page-hero"><div className="tx-shell tx-page-hero-grid"><div><div className="tx-kicker"><span/>{tr("aboutTranos")}</div><h1>{locale==="fa"?"یک استودیو برای عصر بعدی دیجیتال.":locale==="es"?"Un estudio para la próxima era digital.":locale==="de"?"Ein Studio für die nächste digitale Ära.":"A studio for the next digital era."}</h1></div><p>{tr("heroDescription")}</p></div></section>
 <section className="tx-section"><div className="tx-shell tx-about-layout"><div className="tx-about-statement"><span>01 / Philosophy</span><h2>{locale==="fa"?"شفافیت یک مزیت خلاقانه است.":"Clarity is a creative advantage."}</h2></div><div className="tx-rich-copy"><p>{locale==="fa"?"ترانوس برای تیم‌هایی ساخته شده که قالب تکراری، داشبورد عمومی یا برندی شبیه همه نمی‌خواهند.":"Tranos exists for teams that do not want another template, generic dashboard or brand that looks like everyone else."}</p><p>{locale==="fa"?"ما کار دیجیتال را با دیدگاه مشخص می‌سازیم؛ آرام وقتی باید آرام باشد، بیانگر وقتی باید بیانگر باشد، و همیشه متصل به یک هدف واقعی.":"We build digital work with a point of view: calm when it should be calm, expressive when it should be expressive, and grounded in a real objective."}</p><p>{locale==="fa"?"فناوری برای ما تیتر نیست؛ تجربه‌ای است که مردم به خاطر می‌سپارند.":"Technology is never the headline. The headline is the experience people remember."}</p></div></div></section>
 <section className="tx-dark-band"><div className="tx-shell tx-values-grid">{[["01","Precision","Every detail earns its place."],["02","Curiosity","We explore until the idea gets interesting."],["03","Systems","Strong work should scale, not collapse."],["04","Momentum","Launch fast enough to learn."]].map(([n,title,desc])=><div key={n}><span>{n}</span><h3>{title}</h3><p>{locale==="fa"?({Precision:"هر جزئیات باید دلیل داشته باشد.",Curiosity:"آن‌قدر کشف می‌کنیم تا ایده واقعاً جالب شود.",Systems:"کار خوب باید رشد کند، نه اینکه فروبپاشد.",Momentum:"به‌اندازه‌ای سریع عرضه می‌کنیم که بتوانیم یاد بگیریم."} as Record<string,string>)[title]:desc}</p></div>)}</div></section>
 </main><SiteFooter/></>;
}
